name: Update translation files from Transifex 

on:
  schedule:
    - cron: '36 0 * * *'
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest
  
    steps:
      - uses: actions/checkout@v2
      - name: transifex-pull-request-action
        uses: c2corg/transifex-pull-request-action@v3.0.2
        with:
            transifex_token: ${{ secrets.BRANDONS_TRANSIFEX_API_KEY }}
            transifex_organisation: 'OpenMRS'
            transifex_project: 'OpenMRS'
            transifex_resource: 'Order Entry OWA'
            output: 'app/js/translations/'
            locales: 'ar_EG,fr,de,ht,hi,pl,pt_BR,es,tr_TR,uk'
            github_token: ${{ secrets.GITHUB_TOKEN }}

